# Generated by Django 4.1.7 on 2023-03-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonetype', models.CharField(blank=True, max_length=50)),
                ('material', models.CharField(blank=True, max_length=50)),
                ('colour', models.CharField(blank=True, max_length=50)),
                ('accessories', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
